Repository txtdirect/txtdirect, pull requests merged in 2018-08, with the labels that each got.

#88 Update docs
  .travis.yml
  CHANGELOG.md
  docs/README.md
  examples/README.md
Labels: documentation

#96 Include leading slash in URI and Path placeholders
  txtdirect.go
  txtdirect_test.go
Labels: bug

#99 Refactor query to globally remove port from zone and use absolute zone
  path.go
  txtdirect.go
Labels: bug, refactor
